version: '2'
services:
  web:
    build: https://github.com/ethiago/pdhp-front.git
    ports:
      - "8080:8080"
    environment:
      - PORT:8080
      - API_BASE_URL:"http://localhost:8000/v1"
    depends_on:
      - api

  api:
    build: https://github.com/ethiago/pdhp-api.git
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL="mysql://pdhpapi:pdhp_api_pass@localhost:3306/pdhpdb"
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD="mysql_admin_pass"
      - MYSQL_DATABASE="pdhpdb"
      - MYSQL_USER="pdhp_api"
      - MYSQL_PASSWORD="pdhp_api_pass"
